### ISSUE TITLE
Unhandeld exception: input string format incorrect

### ISSUE THREAD

**Issue by masebu** [tslater2006/Trace-Wizard#20]
Hi,

I just discovered Trace Wizard thru the psadmin.io podcast. I was eager to try it... but it fails on all trace files I've thrown it with _Unhandled exception: input string format incorrect_.
That's a rough translation: the actual exception is in french since I'm on a french OS.

Here are all the details I can think of:
Trace Wizard 1.6.1 downloaded today. (about dialog reports 1.3.6988.18709)
OS: Windows 10 1709, enterprise, x64, french
PeopleTools: 8.55.12 on some Linux

My trace file was produced with settings recommended on [Trace Wizard's page](https://tslater2006.github.io/Trace-Wizard/):
* SQL statements
* SQL statement variables
* SQL connect, disconnect, commit, rollback
* SQL fetch 
* All other SQL API calls except SSBs
* Program starts
* External function calls
* Internal function calls

The exception message is
```
System.FormatException: Le format de la chaîne d'entrée est incorrect.
   à System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   à TraceWizard.Processors.SQLProcessor.ProcessLine(String line, Int64 lineNumber)
   à TraceWizard.Processors.TraceProcessor.TraceProcessor_DoWork(Object sender, DoWorkEventArgs e)
   à System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   à System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

Please find attached [inputStringFormatIncorrect.zip](https://github.com/tslater2006/Trace-Wizard/files/2906508/inputStringFormatIncorrect.zip)
* details of the error
* a sample trace file

Can you tell whether the problem lies in the trace file itself or because I'm on a french OS ? If so is there anything that can be done to be OS-language independent ?

Let me know if you need more info.

Thanks

**Comment by tslater2006** [comment]
Hey, thanks for reporting this issue, let me take a look

**Comment by tslater2006** [comment]
The trace seems to load fine (albeit with some message boxes about unsupported PPC objects). I think its an environment issue with the format of decimal numbers. Let me look at how to solve this.

Basically because the machine is in French, i believe it is expecting comma (,) to be used for the decimal place and not the period (.) which is what the trace files have.

**Comment by tslater2006** [comment]
I've pushed changes that should fix the reported issue. Attached you'll find a new build with this fix in place in case you are unable to build from source. 
[Trace.Wizard.1.6.1-CultureFix.zip](https://github.com/tslater2006/Trace-Wizard/files/2906673/Trace.Wizard.1.6.1-CultureFix.zip)

**Comment by enriquepizana** [comment]
Incredible turn around time!

**Comment by masebu** [comment]
Hi,

I see you fixed both the locale issue and unknown objects.
That new build loads my other traces all right.

thanks for the very quick fix and thanks for making that tool available.
