### ISSUE TITLE
List of PeopleCode objects and events

### ISSUE THREAD

**Issue by iversond** [tslater2006/Trace-Wizard#5]
Similar to #1, a list of PeopleCode objects and events in the trace would be nice to see. The list would give developers a quick list of objects to research when debugging.

**Comment by tslater2006** [comment]
Marking as enhancement.

**Comment by tslater2006** [comment]
This will take more work than originally thought, postponing so I can get a release with the new bugfixes out today.

**Comment by tslater2006** [comment]
Fixed by commit ac90fff :)
